openapi: "3.0.3"
info:
  title: "course_api API"
  description: "course_api API"
  version: "1.0.0"
servers:
- url: "https://course_api"
paths:
  /hello:
    get:
      summary: "GET hello"
      operationId: "sayHello1"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /welcome:
    get:
      summary: "GET welcome"
      operationId: "sayHello2"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /bye:
    get:
      summary: "GET bye"
      operationId: "sayBye"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /bye*:
    get:
      summary: "GET bye*"
      operationId: "sayBye1"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /bye/{variable}:
    get:
      summary: "GET bye/*"
      operationId: "sayBye2"
      parameters:
        - name: variable
          in: path
          required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /bye/<unknown>:
    get:
      summary: "GET bye/${..}"
      operationId: "sayBye3"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /bye*/{variable}/test/<unknown>:
    get:
      summary: "GET bye*/*/test/${..}"
      operationId: "sayBye4"
      parameters:
        - name: variable
          in: path
          required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /hi:
    get:
      summary: "GET hi"
      operationId: "sayHi"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /api/sorry:
    get:
      summary: "GET api/sorry"
      operationId: "saySorry1"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    put:
      summary: "PUT api/sorry"
      operationId: "saySorry2"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    post:
      summary: "POST api/sorry"
      operationId: "saySorry3"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    delete:
      summary: "DELETE api/sorry"
      operationId: "saySorry4"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    options:
      summary: "OPTIONS api/sorry"
      operationId: "saySorry5"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    head:
      summary: "HEAD api/sorry"
      operationId: "saySorry6"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    patch:
      summary: "PATCH api/sorry"
      operationId: "saySorry7"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    trace:
      summary: "TRACE api/sorry"
      operationId: "saySorry8"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /:
    get:
      summary: "GET "
      operationId: "redirectRequest1"
      responses:
        "200":
          description: "OK"
  /redirect:
    get:
      summary: "GET redirect"
      operationId: "redirectRequest2"
      responses:
        "200":
          description: "OK"
  /<unknown>:
    get:
      summary: "GET ${..}"
      operationId: "redirectAll"
      responses:
        "200":
          description: "OK"
